---
- name: Install Docker and build Docker image
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache (for Ubuntu)
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install required packages for Docker
      package:
        name:
          - docker
          - docker-compose
      when: ansible_distribution == "Ubuntu"

    - name: Start Docker service
      service:
        name: docker
        state: started
      when: ansible_distribution == "Ubuntu"

    - name: Build Docker image
      command: "docker build -t apache1.0 /home/daniela/CPE232_RABANG_HOA11/file"
      args:
        executable: /bin/bash
      when: ansible_distribution == "Ubuntu"

    - name: Install Docker on CentOS
      yum:
        name: docker
        state: present
      when: ansible_distribution == "CentOS"

    - name: Start Docker service
      service:
        name: docker
        state: started
      when: ansible_distribution == "CentOS"

    - name: Build Docker image
      command: "docker build -t apache1.0 /home/daniela/CPE232_RABANG_HOA11/file"
      when: ansible_distribution == "CentOS"

